-- Insertar datos en tipos_habitaciones
INSERT INTO tipos_habitaciones (nombre, descripcion) VALUES
                                                         ('Individual', 'Habitación para una persona con una cama individual'),
                                                         ('Doble', 'Habitación para dos personas con dos camas individuales'),
                                                         ('Matrimonial', 'Habitación para dos personas con una cama matrimonial'),
                                                         ('Suite', 'Habitación de lujo con comodidades adicionales'),
                                                         ('Familiar', 'Habitación para familias con varias camas'),
                                                         ('Económica', 'Habitación básica para una o dos personas'),
                                                         ('Deluxe', 'Habitación espaciosa con servicios premium'),
                                                         ('Estudio', 'Habitación con área de trabajo y cama'),
                                                         ('Ático', 'Habitación ubicada en el último piso con vistas'),
                                                         ('Cabaña', 'Habitación estilo rústico fuera del edificio principal'),
                                                         ('Premium', 'Habitación con servicios exclusivos y lujo'),
                                                         ('Estándar', 'Habitación estándar con servicios básicos'),
                                                         ('Triple', 'Habitación para tres personas con tres camas individuales'),
                                                         ('Dúplex', 'Habitación en dos niveles con escaleras internas'),
                                                         ('King', 'Habitación con cama tamaño King'),
                                                         ('Queen', 'Habitación con cama tamaño Queen'),
                                                         ('Mini Suite', 'Habitación más pequeña que una suite estándar'),
                                                         ('Bungaló', 'Habitación independiente estilo tropical'),
                                                         ('Estudio Deluxe', 'Habitación estudio con servicios adicionales'),
                                                         ('Suite Presidencial', 'La habitación más lujosa y espaciosa del hotel');

-- Insertar datos en tipos_camas
INSERT INTO tipos_camas (nombre, descripcion) VALUES
                                                  ('Individual', 'Cama para una persona'),
                                                  ('Matrimonial', 'Cama para dos personas'),
                                                  ('Queen', 'Cama más grande que la matrimonial'),
                                                  ('King', 'Cama más grande que la Queen'),
                                                  ('Super King', 'Cama extra grande para lujo'),
                                                  ('Literas', 'Dos camas en formato litera'),
                                                  ('Futon', 'Cama estilo sofá convertible'),
                                                  ('Cama Infantil', 'Cama para niños pequeños'),
                                                  ('Cama Plegable', 'Cama que se puede guardar fácilmente'),
                                                  ('Cama Redonda', 'Cama con diseño circular'),
                                                  ('Cama de Agua', 'Cama con colchón de agua'),
                                                  ('Sofá Cama', 'Cama convertible en sofá'),
                                                  ('Cama Flotante', 'Cama suspendida del suelo'),
                                                  ('Cama Doble', 'Dos camas individuales juntas'),
                                                  ('Cama de Hospital', 'Cama ajustable para necesidades especiales'),
                                                  ('Cama Nido', 'Cama con un colchón adicional deslizante'),
                                                  ('Cama de Madera', 'Cama con estructura de madera clásica'),
                                                  ('Cama Canopy', 'Cama con dosel para mayor privacidad'),
                                                  ('Cama Twin XL', 'Cama más larga que una individual estándar'),
                                                  ('Cama Modular', 'Cama que se puede configurar en diferentes formas');

-- Insertar datos en sedes
INSERT INTO sedes (nombre, ciudad, pais, direccion, estado) VALUES
                                                                ('Hotel Central', 'Lima', 'Perú', 'Av. Central 123', 'DISPONIBLE'),
                                                                ('Hotel Sol', 'Cusco', 'Perú', 'Calle Sol 456', 'DISPONIBLE'),
                                                                ('Hotel Arena', 'Piura', 'Perú', 'Av. Arena 789', 'NO DISPONIBLE'),
                                                                ('Hotel Andes', 'Arequipa', 'Perú', 'Calle Andes 101', 'DISPONIBLE'),
                                                                ('Hotel Mar', 'Trujillo', 'Perú', 'Av. Mar 202', 'DISPONIBLE'),
                                                                ('Hotel Lago', 'Puno', 'Perú', 'Calle Lago 303', 'DISPONIBLE'),
                                                                ('Hotel Selva', 'Iquitos', 'Perú', 'Av. Selva 404', 'NO DISPONIBLE'),
                                                                ('Hotel Sierra', 'Huancayo', 'Perú', 'Calle Sierra 505', 'DISPONIBLE'),
                                                                ('Hotel Norte', 'Chiclayo', 'Perú', 'Av. Norte 606', 'DISPONIBLE'),
                                                                ('Hotel Sur', 'Tacna', 'Perú', 'Calle Sur 707', 'DISPONIBLE'),
                                                                ('Hotel Este', 'Tarapoto', 'Perú', 'Av. Este 808', 'DISPONIBLE'),
                                                                ('Hotel Oeste', 'Ica', 'Perú', 'Calle Oeste 909', 'DISPONIBLE'),
                                                                ('Hotel Centro', 'Lima', 'Perú', 'Av. Centro 1010', 'DISPONIBLE'),
                                                                ('Hotel Azul', 'Cusco', 'Perú', 'Calle Azul 1111', 'DISPONIBLE'),
                                                                ('Hotel Verde', 'Piura', 'Perú', 'Av. Verde 1212', 'DISPONIBLE'),
                                                                ('Hotel Amarillo', 'Trujillo', 'Perú', 'Calle Amarillo 1313', 'DISPONIBLE'),
                                                                ('Hotel Blanco', 'Arequipa', 'Perú', 'Av. Blanco 1414', 'DISPONIBLE'),
                                                                ('Hotel Negro', 'Puno', 'Perú', 'Calle Negro 1515', 'DISPONIBLE'),
                                                                ('Hotel Dorado', 'Iquitos', 'Perú', 'Av. Dorado 1616', 'DISPONIBLE'),
                                                                ('Hotel Plateado', 'Tacna', 'Perú', 'Calle Plateado 1717', 'DISPONIBLE');

-- Insertar datos en habitaciones
INSERT INTO habitaciones (nombre, precio_noche, capacidad_max, estado, imagen_url, id_tipo_cama, id_tipo_habitacion) VALUES
                                                                                                                         ('Habitación 101', 100.00, 2, 'DISPONIBLE', 'url_101.jpg', 1, 1),
                                                                                                                         ('Habitación 102', 120.00, 2, 'DISPONIBLE', 'url_102.jpg', 2, 2),
                                                                                                                         ('Habitación 103', 150.00, 4, 'DISPONIBLE', 'url_103.jpg', 3, 3),
                                                                                                                         ('Habitación 104', 200.00, 2, 'OCUPADA', 'url_104.jpg', 4, 4),
                                                                                                                         ('Habitación 105', 80.00, 1, 'DISPONIBLE', 'url_105.jpg', 5, 1),
                                                                                                                         ('Habitación 106', 250.00, 3, 'RESERVADA', 'url_106.jpg', 6, 5),
                                                                                                                         ('Habitación 107', 300.00, 4, 'DISPONIBLE', 'url_107.jpg', 7, 6),
                                                                                                                         ('Habitación 108', 180.00, 3, 'MANTENIMIENTO', 'url_108.jpg', 8, 7),
                                                                                                                         ('Habitación 109', 120.00, 2, 'DISPONIBLE', 'url_109.jpg', 9, 8),
                                                                                                                         ('Habitación 110', 90.00, 1, 'DISPONIBLE', 'url_110.jpg', 10, 1),
                                                                                                                         ('Habitación 111', 170.00, 2, 'OCUPADA', 'url_111.jpg', 11, 9),
                                                                                                                         ('Habitación 112', 260.00, 3, 'DISPONIBLE', 'url_112.jpg', 12, 10),
                                                                                                                         ('Habitación 113', 400.00, 5, 'RESERVADA', 'url_113.jpg', 13, 11),
                                                                                                                         ('Habitación 114', 600.00, 6, 'DISPONIBLE', 'url_114.jpg', 14, 12),
                                                                                                                         ('Habitación 115', 320.00, 4, 'OCUPADA', 'url_115.jpg', 15, 13),
                                                                                                                         ('Habitación 116', 150.00, 2, 'DISPONIBLE', 'url_116.jpg', 16, 14),
                                                                                                                         ('Habitación 117', 130.00, 2, 'DISPONIBLE', 'url_117.jpg', 17, 15),
                                                                                                                         ('Habitación 118', 170.00, 3, 'DISPONIBLE', 'url_118.jpg', 18, 16),
                                                                                                                         ('Habitación 119', 500.00, 5, 'OCUPADA', 'url_119.jpg', 19, 17),
                                                                                                                         ('Habitación 120', 550.00, 6, 'DISPONIBLE', 'url_120.jpg', 20, 18);
