-- Insertar datos en tipos_habitaciones con descripciones más extensas
INSERT INTO tipos_habitaciones (nombre, descripcion) VALUES
                                                         ('Individual', 'Habitación diseñada para una persona, equipada con una cama individual y todas las comodidades básicas, ideal para viajes en solitario.'),
                                                         ('Doble', 'Habitación con dos camas individuales, perfecta para amigos o colegas que desean compartir alojamiento con privacidad.'),
                                                         ('Matrimonial', 'Habitación acogedora con una cama matrimonial, ideal para parejas que buscan comodidad y tranquilidad.'),
                                                         ('Suite', 'Habitación lujosa que incluye un área de sala de estar independiente, equipada con muebles premium y servicios adicionales.'),
                                                         ('Familiar', 'Espacio amplio para familias, con camas adicionales y comodidades adaptadas para niños y adultos.'),
                                                         ('Deluxe', 'Habitación de lujo con decoración sofisticada, vistas impresionantes y servicios exclusivos para una experiencia superior.'),
                                                         ('Estándar', 'Habitación básica y funcional, equipada con lo esencial para una estancia cómoda y económica.'),
                                                         ('Junior Suite', 'Habitación espaciosa con un área de descanso adicional, perfecta para quienes buscan comodidad extra.'),
                                                         ('Triple', 'Habitación con capacidad para tres personas, equipada con tres camas individuales o combinaciones personalizadas.'),
                                                         ('Cuádruple', 'Habitación ideal para grupos, con espacio y camas suficientes para alojar a cuatro personas cómodamente.'),
                                                         ('Presidencial', 'Suite de alta gama con comodidades exclusivas, mobiliario de lujo y amplios espacios, destinada a huéspedes exigentes.'),
                                                         ('Economy', 'Habitación económica, equipada con los servicios básicos necesarios para una estancia cómoda y accesible.'),
                                                         ('Studio', 'Habitación estilo estudio, con un diseño integrado que combina áreas de descanso, trabajo y relajación.'),
                                                         ('Superior', 'Habitación de categoría superior, con un diseño moderno y servicios mejorados para una experiencia especial.'),
                                                         ('Villa', 'Espacio privado con varias habitaciones, áreas comunes y servicios exclusivos, ideal para grupos grandes o familias.'),
                                                         ('Penthouse', 'Ático lujoso con vistas panorámicas, decoración de diseño y comodidades de alta gama.'),
                                                         ('Business', 'Habitación especialmente diseñada para viajeros de negocios, con escritorio, buena iluminación y servicios de oficina.'),
                                                         ('Accessible', 'Habitación completamente adaptada para personas con discapacidades, con instalaciones accesibles y cómodas.'),
                                                         ('Con balcón', 'Habitación equipada con un balcón privado, ideal para disfrutar del aire fresco y vistas exteriores.'),
                                                         ('Con vista', 'Habitación con vistas espectaculares, ya sea al mar, montañas, ciudad o paisajes naturales.');

-- Insertar datos en tipos_camas con descripciones más extensas
INSERT INTO tipos_camas (nombre, descripcion) VALUES
                                                  ('Individual', 'Cama de tamaño estándar para una persona, ideal para habitaciones individuales o compartidas.'),
                                                  ('Matrimonial', 'Cama doble para dos personas, diseñada para brindar comodidad y espacio adecuado para parejas.'),
                                                  ('King Size', 'Cama extragrande, ideal para quienes buscan espacio adicional para un descanso confortable.'),
                                                  ('Queen Size', 'Cama más grande que una matrimonial, perfecta para parejas que prefieren espacio extra.'),
                                                  ('Super King Size', 'Cama de lujo con dimensiones superiores, proporcionando la máxima comodidad y amplitud.'),
                                                  ('Literas', 'Conjunto de camas apiladas verticalmente, ideales para optimizar el espacio en habitaciones familiares o grupales.'),
                                                  ('Futón', 'Cama convertible que también puede usarse como sofá, perfecta para habitaciones multifuncionales.'),
                                                  ('Sofá cama', 'Sofá que se transforma en una cama, ideal para alojar invitados o para espacios reducidos.'),
                                                  ('Cuna', 'Cama pequeña diseñada específicamente para bebés, con barreras de seguridad y colchones cómodos.'),
                                                  ('Tatami', 'Cama de estilo japonés, colocada sobre una plataforma baja, conocida por su diseño minimalista y relajante.'),
                                                  ('Colchón inflable', 'Cama portátil y ligera, inflable para su uso temporal, ideal para huéspedes adicionales.'),
                                                  ('Twin', 'Dos camas individuales colocadas separadamente, populares en habitaciones dobles para amigos o colegas.'),
                                                  ('Murphy', 'Cama plegable que se guarda en la pared cuando no está en uso, optimizando el espacio disponible.'),
                                                  ('Diván', 'Cama multifuncional estilo chaise longue, ideal para salas de estar o áreas de descanso.'),
                                                  ('California King', 'Cama extragrande con dimensiones especialmente largas, ideal para personas altas.'),
                                                  ('Redonda', 'Cama moderna con forma circular, utilizada para dar un toque único y sofisticado a la habitación.'),
                                                  ('Extra', 'Cama adicional que se puede colocar temporalmente en la habitación según la solicitud del huésped.'),
                                                  ('Triple', 'Cama de tres niveles apilados, especialmente diseñada para dormitorios compactos y grupos grandes.'),
                                                  ('Hidromasaje', 'Cama equipada con tecnología de masajes, proporcionando relajación y bienestar.'),
                                                  ('Suspendida', 'Cama colgante que se balancea suavemente, ofreciendo una experiencia única y relajante.');


-- Insertar datos en sedes
INSERT INTO sedes (nombre, ciudad, pais, direccion, estado) VALUES
                                                                ('Hotel Centro', 'Lima', 'Perú', 'Av. Central 123', 'DISPONIBLE'),
                                                                ('Hotel Sol', 'Cusco', 'Perú', 'Calle del Sol 456', 'DISPONIBLE'),
                                                                ('Hotel Andino', 'Arequipa', 'Perú', 'Av. Andina 789', 'DISPONIBLE'),
                                                                ('Hotel Pacifico', 'Trujillo', 'Perú', 'Av. Pacífico 321', 'DISPONIBLE'),
                                                                ('Hotel Amazonia', 'Iquitos', 'Perú', 'Calle Amazonas 654', 'DISPONIBLE'),
                                                                ('Hotel Colonial', 'Puno', 'Perú', 'Calle Real 223', 'DISPONIBLE');

-- Insertar datos en habitaciones
INSERT INTO habitaciones (nombre, precio_noche, capacidad_max, estado, imagen_url, id_tipo_cama, id_tipo_habitacion, id_sede) VALUES
                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 1),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 1),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 1),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 1),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 1),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 1),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 1),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 1),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 1),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 1),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 1),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 1),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 1),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 1),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 1),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 1),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 1),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 1),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 1),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 1),

                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 2),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 2),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 2),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 2),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 2),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 2),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 2),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 2),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 2),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 2),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 2),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 2),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 2),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 2),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 2),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 2),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 2),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 2),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 2),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 2),

                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 3),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 3),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 3),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 3),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 3),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 3),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 3),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 3),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 3),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 3),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 3),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 3),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 3),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 3),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 3),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 3),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 3),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 3),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 3),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 3),

                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 4),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 4),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 4),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 4),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 4),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 4),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 4),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 4),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 4),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 4),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 4),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 4),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 4),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 4),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 4),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 4),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 4),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 4),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 4),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 4),

                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 5),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 5),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 5),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 5),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 5),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 5),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 5),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 5),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 5),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 5),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 5),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 5),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 5),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 5),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 5),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 5),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 5),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 5),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 5),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 5),

                                                                                                                         ('Suite Andina', 150.00, 2, 'DISPONIBLE', 'suite_andina.jpg', 1, 1, 6),
                                                                                                                         ('Doble Sol', 200.00, 2, 'DISPONIBLE', 'doble_sol.jpg', 2, 2, 6),
                                                                                                                         ('Matrimonial Imperial', 250.00, 3, 'DISPONIBLE', 'matrimonial_imperial.jpg', 3, 3, 6),
                                                                                                                         ('Junior Suite Real', 300.00, 4, 'DISPONIBLE', 'junior_suite_real.jpg', 4, 4, 6),
                                                                                                                         ('Estándar Pacífico', 120.00, 1, 'DISPONIBLE', 'estandar_pacifico.jpg', 1, 1, 6),
                                                                                                                         ('Deluxe Nevado', 400.00, 2, 'DISPONIBLE', 'deluxe_nevado.jpg', 3, 5, 6),
                                                                                                                         ('Suite Presidencial Amazonas', 500.00, 5, 'DISPONIBLE', 'suite_presidencial_amazonas.jpg', 4, 6, 6),
                                                                                                                         ('Familiar Costero', 350.00, 2, 'DISPONIBLE', 'familiar_costero.jpg', 2, 7, 6),
                                                                                                                         ('Villa Paraíso', 600.00, 6, 'DISPONIBLE', 'villa_paraiso.jpg', 5, 8, 6),
                                                                                                                         ('Suite Laguna Azul', 450.00, 4, 'DISPONIBLE', 'suite_laguna_azul.jpg', 3, 9, 6),
                                                                                                                         ('Penthouse Urbano', 550.00, 5, 'DISPONIBLE', 'penthouse_urbano.jpg', 4, 10, 6),
                                                                                                                         ('Suite Bosque', 300.00, 3, 'DISPONIBLE', 'suite_bosque.jpg', 2, 11, 6),
                                                                                                                         ('Matrimonial Histórico', 700.00, 6, 'DISPONIBLE', 'matrimonial_historico.jpg', 5, 12, 6),
                                                                                                                         ('Junior Suite Playa', 350.00, 4, 'DISPONIBLE', 'junior_suite_playa.jpg', 3, 13, 6),
                                                                                                                         ('Villa Imperial', 800.00, 8, 'DISPONIBLE', 'villa_imperial.jpg', 4, 14, 6),
                                                                                                                         ('Deluxe Sierra', 600.00, 5, 'DISPONIBLE', 'deluxe_sierra.jpg', 3, 15, 6),
                                                                                                                         ('Suite Presidencial Nevado', 900.00, 7, 'DISPONIBLE', 'suite_presidencial_nevado.jpg', 5, 16, 6),
                                                                                                                         ('Habitación Familiar Selva', 500.00, 4, 'DISPONIBLE', 'familiar_selva.jpg', 3, 17, 6),
                                                                                                                         ('Suite Con Vista Estrella', 450.00, 3, 'DISPONIBLE', 'suite_con_vista_estrella.jpg', 4, 18, 6),
                                                                                                                         ('Junior Suite Montaña', 400.00, 2, 'DISPONIBLE', 'junior_suite_montaña.jpg', 2, 19, 6);

